/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj4_lokal;

import static java.lang.Math.abs;
import static java.lang.Math.acos;
import static java.lang.Math.cos;
import static java.lang.Math.sin;
import static java.lang.Math.tan;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mo1005
 */
public class Proj4_Lokal extends javax.swing.JFrame {

    /**
     * Creates new form Proj4_Lokal
     */
    public Proj4_Lokal() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        re1 = new javax.swing.JTextField();
        ho1 = new javax.swing.JTextField();
        la1 = new javax.swing.JTextField();
        lo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        re2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ho2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        la2 = new javax.swing.JTextField();
        lo2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        projButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ergebnis = new javax.swing.JTextArea();
        abstand = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        winkelText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        skal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        abstandwgs = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ho1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ho1KeyReleased(evt);
            }
        });

        jLabel1.setText("x");

        jLabel2.setText("y");

        jLabel3.setText("Latitude/ Breite");

        jLabel4.setText("Longitude / Länge");

        jLabel5.setText("Coordinate 1");

        jLabel6.setText("Local");

        jLabel7.setText("WGS84 EPSG 4326");

        jLabel8.setText("Coordinate 2");

        jLabel9.setText("Local");

        ho2.setEditable(false);

        jLabel10.setText("WGS84 EPSG 4326");

        jLabel11.setText("x");

        jLabel12.setText("y");

        jLabel13.setText("Latitude/ Breite");

        jLabel14.setText("Longitude / Länge");

        projButton.setText("Calculate Proj4");
        projButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projButtonActionPerformed(evt);
            }
        });

        ergebnis.setColumns(20);
        ergebnis.setRows(5);
        jScrollPane1.setViewportView(ergebnis);

        jLabel15.setText("Distance local [km]");

        jLabel16.setText("Roatation angle[°]");

        jLabel17.setText("Scalefactor");

        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("Both local coordinates have to have the same Y value");

        jLabel19.setText("Distance wgs [km]");

        jLabel20.setText("The scale is not included in the proj4 String - it's only for evaluation purposes ");

        jLabel21.setText("Usage in QGIS:");

        jLabel22.setText("Settings -> Custom CRS -> Push the green plus");

        jLabel23.setText("Insert a new name");

        jLabel24.setText("Copy the Proj4 text to \"Parameters\"");

        jLabel25.setText("Click on NewCRS in the overview");

        jLabel26.setText("Right click on the layer -> Set Layer CRS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(re1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(ho1)))
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(la1)
                                            .addComponent(lo1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ho2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(re2)))
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(la2)
                                            .addComponent(lo2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(projButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abstand)
                            .addComponent(winkelText)
                            .addComponent(skal)
                            .addComponent(abstandwgs))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(la1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(47, 47, 47)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(re1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(re2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abstandwgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(skal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(winkelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projButtonActionPerformed
        /*
        
        
        Zwei Ausführungen müssen beachtet werden
        1:  Ist das lokale System perfekt genordet, so reicht es die Koordinate des Ursprungs in WGS 84 in den Proj4 String einzugeben
        2:  Ist das lokale System nicht genau genordet, so muss der Rotationswinkel zwischen dem lokalen und dem Weltsystem berechnet werden
            Dazu sind je zwei Koordinaten notwendig, die beide auf dem gleichen Hochwert liegen
        
        Ist die erste Koordiante nicht im Ursprung des lokalen Systems (z.B.: Nullpunkt auf der Grabung ist 1000/1000), muss ein False Easting oder False Northing mit übergeben werden
        
        Die Berechnungen zu den WGS Koordinaten erfolgen nach
        http://www.gassipods.de/downloads/gcexceltool_v2.xls
        
        
        Die Berechnung der Winkels zwischen de
        
        Fehler möglicherweise durch den Unterschied von Loxodrome und Orthodrome
        
        */
        
        
        double x1,h1,x2,h2,wgs_x1,wgs_x2,wgs_y1,wgs_y2,wgs_x1_bg,wgs_x2_bg,wgs_y1_bg,wgs_y2_bg;
        DecimalFormat df1 = new DecimalFormat("0.0000");
        DecimalFormat df2 = new DecimalFormat("0.00");
        try{
        //lokale Koordinaten auslesen
         x1 = Double.parseDouble(re1.getText());
         h1 = Double.parseDouble(ho1.getText());
         x2 = Double.parseDouble(re2.getText());
         h2 = Double.parseDouble(ho2.getText());
        //wgs Koordinaten auslesen
         wgs_x1 = Double.parseDouble(la1.getText());
         wgs_y1 = Double.parseDouble(lo1.getText());        
         wgs_x2 = Double.parseDouble(la2.getText());        
         wgs_y2 = Double.parseDouble(lo2.getText());

         
         
         
        //Punkt 2 muss rechts von Punkt 1 liegen
        if (x1 >= x2){
        JOptionPane.showMessageDialog(null, "Koordinate 1 muss westlich von Koordinate 2 liegen!", "Nicht möglich", JOptionPane.ERROR_MESSAGE);             
        } else {
        //Starten der Berechnung
        //WGS Koordinaten in Bogenmaß
        wgs_x1_bg = wgs_x1*Math.PI/180;
        wgs_y1_bg = wgs_y1*Math.PI/180;
        wgs_x2_bg = wgs_x2*Math.PI/180;
        wgs_y2_bg = wgs_y2*Math.PI/180;

        
        //Schritt 1
        double a = (sin(wgs_x1_bg))*(sin(wgs_x2_bg));
        double b= ((cos(wgs_x1_bg))*(cos(wgs_x2_bg))*(cos((wgs_y1-wgs_y2)*Math.PI/180)));
        
        double s1 = a+ b;
        System.out.println(s1);

        
        double grad = 0;
        double s2 = abs(acos(sin(wgs_x2_bg)/sin(acos(s1))/cos(wgs_x1_bg)-tan(wgs_x1_bg)/tan(acos(s1)))*180/Math.PI-grad);

        double winkel = (90-s2)*-1;

        double falsex = 0;
        double falsey = 0;
        
        if (x1 > 0){
            falsex = x1;
        }
        if (h1 > 0){
            falsey = h1;
        }        
        
        String proj4 = null;
        if (winkel == 0){
            //Ohne Rotation ist eine einfache Mercator projektion ausreichend
        proj4 =  "+proj=tmerc +lat_0= " + wgs_x1 + " +lon_0= " + wgs_y1 + " +k=1 +x_0= "+falsex+" +y_0= "+falsey+" +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";  
        } else {
            //Mit Rotation ist eine Oblique Mercator nötig
            //siehe http://gis.stackexchange.com/questions/83861/using-customized-coordinate-system-for-archaeological-site-data
        proj4 = "+proj=omerc +lat_0= " + wgs_x1 +  " +lonc= "+wgs_y1+" +alpha= " +winkel+" +k=1 +x_0= "+falsex+" +y_0= "+falsey+" +gamma=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";
        }
        double abstand_lokal = Math.sqrt(Math.pow((x2-x1),2)+Math.pow((h2-h1),2));
        double abstand_wgs =   (6371.229*acos(s1))*1000;

        abstand.setText(String.valueOf(df1.format(abstand_lokal/1000)));
        abstandwgs.setText(String.valueOf(df1.format(abstand_wgs/1000)));
        winkelText.setText(String.valueOf(df2.format(winkel)));
        /*Skalierung berechenen
        
        Skalierung wird nur angezeigt und nicht als Parameter im Proj4 String eingesetzt, da sich im Test gezeigt hat, dass die Ungenauigkeit höher wird
        Ist der Faktor sehr hoch zeigt es an, dass die Koordinaten nicht stimmen können
        
        
        */
        if(abstand_lokal >= abstand_wgs){
        skal.setText(String.valueOf(abstand_lokal/abstand_wgs));            
        } else if (abstand_lokal < abstand_wgs){
        skal.setText(String.valueOf(abstand_wgs/abstand_lokal));            
        }

        ergebnis.setText(proj4);
        

        }         
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Bitte korrekten Zahlenwert eingeben!", "Nicht möglich", JOptionPane.ERROR_MESSAGE);            
        }
        



        
        
    }//GEN-LAST:event_projButtonActionPerformed

    private void ho1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ho1KeyReleased
        ho2.setText(ho1.getText()) ;
    }//GEN-LAST:event_ho1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proj4_Lokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proj4_Lokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proj4_Lokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proj4_Lokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proj4_Lokal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abstand;
    private javax.swing.JTextField abstandwgs;
    private javax.swing.JTextArea ergebnis;
    private javax.swing.JTextField ho1;
    private javax.swing.JTextField ho2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField la1;
    private javax.swing.JTextField la2;
    private javax.swing.JTextField lo1;
    private javax.swing.JTextField lo2;
    private javax.swing.JButton projButton;
    private javax.swing.JTextField re1;
    private javax.swing.JTextField re2;
    private javax.swing.JTextField skal;
    private javax.swing.JTextField winkelText;
    // End of variables declaration//GEN-END:variables
}
